Adding logfile output to consumer_test, instead of outputting to CI (#448)
Changed output of consumers to files to unblock the pipe. 

Also added Summary of the consumers to the Github summary page

Full logs are printed & downloadable if wanted via the Github Artifacts.

diff --git a/.github/workflows/consumer_test.yml b/.github/workflows/consumer_test.yml
--- a/.github/workflows/consumer_test.yml
+++ b/.github/workflows/consumer_test.yml
@@ -44,8 +44,27 @@ jobs:
       - name: Run Consumer tests
 
         run: |
-          set -o pipefail
-          .venv_docs/bin/python -m pytest -s -v src/tests/ --repo="$CONSUMER" --junitxml="reports/${{ matrix.consumer }}.xml" | tee "reports/${{ matrix.consumer }}.log"
+          pytest_rc=0
+          .venv_docs/bin/python -m pytest -vv src/tests/ \
+          --repo="$CONSUMER" \
+          --junitxml="reports/${{ matrix.consumer }}.xml" \
+          || pytest_rc=$?
+
+
+          if [ -f "consumer_test.log" ]; then
+            src_log="consumer_test.log"
+          else
+            echo "consumer_test.log not found; expected at ./consumer_test.log"
+          exit ${pytest_rc:-1}
+          fi
+
+          dest_log="reports/${{ matrix.consumer }}.log"
+          mv "$src_log" "$dest_log"
+
+          tail -n 15 "$dest_log" >> "$GITHUB_STEP_SUMMARY"
+
+          cat "$dest_log"
+          exit $pytest_rc
         env:
           FORCE_COLOR: "1"
           TERM: xterm-256color
